//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuSystem.Models
{
    using System;
    using System.Collections.Generic;
    //添加模型数据注解的命名空间
    using System.ComponentModel.DataAnnotations;
    public partial class Student
    {
        public int StuID { get; set; }
        [Required(ErrorMessage = "姓名是必填项")]
        public string Name { get; set; }
        [Required(ErrorMessage ="密码是必填项")]
        [RegularExpression("[A-Za-z0-9]{6,12}",ErrorMessage = "密码只能由数字和字母组成的6-12位的字符")]
        public string Password { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Grades { get; set; }
        [MaxLength(50,ErrorMessage ="内容不能超过50字")]
        public string Intro { get; set; }
        public string Agreest { get; set; }
        [Required(ErrorMessage ="请确认密码")]
        [Compare("Password",ErrorMessage ="密码不一致，请重新输入")]
        public string Password2 { get; set; }
        [Range(typeof(int),"10","30",ErrorMessage ="年龄应在10-30岁之间")]
        public Nullable<int> Age { get; set; }
    
        public virtual Grades Grades1 { get; set; }
    }
}
