//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paper()
        {
            this.Answer = new HashSet<Answer>();
            this.Topic = new HashSet<Topic>();
        }
        [Display(Name ="试卷编号")]
        public int PaperID { get; set; }
        [Required(ErrorMessage = ("试卷名是必填项"))]
        [Display(Name = "试卷名")]
        public string PaperName { get; set; }
        [Display(Name = "试卷描述")]
        [Required(ErrorMessage = ("试卷描述是必填项"))]
        [StringLength(20,ErrorMessage ="试卷描述不能超过20字")]
        
        public string PaperExplain { get; set; }
        [Display(Name = "试卷时长")]
        [Required(ErrorMessage = "试卷时长是必填项")]       
        [Range(0,120,ErrorMessage ="试卷时长应在0-120分钟之内")]
        public int PaperTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topic { get; set; }
    }
}
