//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public int TeacherID { get; set; }
        [Display(Name ="老师名")]
        public string TeacherName { get; set; }
        [Display(Name = "登录名")]
        [Required(ErrorMessage = "登录名是必填项")]
        public string TeacherLoginName { get; set; }
        [Display(Name = "密码")]
        [Required(ErrorMessage = "密码是必填项")]
        public string TeacherLoginPwd { get; set; }
        public string TeacherPhone { get; set; }
        public string TeacherEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answer { get; set; }
    }
}
